### PR TITLE
docs: update license type to ISC

### PR DESCRIPTION
**Pull request by Muunatic**
## Changes
update wrong license type in readme.md file

### CODE REVIEW

**Comment by Muunatic** [comment]
merge

**Comment by Muunatic** [comment]
bypassing review as it's not crucial

**Comment by Muunatic** [comment]
bypassing review as it's not crucial (appoved by 2nd acc)

**Review by Ichigoez — APPROVED** [review]

**Comment by Muunatic** [comment]
ready to merge

**Pull request merged**
