### PR TITLE
fix: inaccessible pull_request number in workflow_run

### PR DESCRIPTION
**Pull request by Muunatic**
automaton encountered an error where the pull_request[0].number wasn't accessible within the workflow_run. pull_request would return an empty array when pull requests are made from forked repositories (outside main repository).

image

### CODE REVIEW

**Comment by Muunatic** [comment]
this fix is temporary and has not been tested to confirm its completely resolves the issue.

**Comment by HarunamiYaki** [comment]
It seems the issue stems from the API indicating an empty pull request array https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28. Even though this isn't from codebase issue itself but rather than from the [GitHub API](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28).

**Comment by Muunatic** [comment]
> It seems the issue stems from the API indicating an empty pull request array https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28. Even though this isn't from codebase issue itself but rather than from the [GitHub API](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28).

indeed, checks_run are returning empty pull_request array data if pr comes from a forked repo. that is why i need to get pr author pulls list from the head_branch to get the exact pull_request data. for now it only works on the public repository and i need to test if the payload can still get pull_request data if pr comes from a private forked repo.

**Comment by Muunatic** [comment]
i'm going to skip the review for now. i'll convert this prs to draft to double-check everything is good.

**Comment by HarunamiYaki** [comment]
I noticed the code might be pulling the wrong pull request if there are multiple open PRs. When you're fetching the PR number using res.data[0].number, it might not always grab the right one if there are multiple open PRs. If the workflow gets triggered on `Pull Request #2` but you fetch res.data[0], it could mistakenly refer to `Pull Request #1`.

A possible fix could be filtering the data by `head_sha`. This tweak should help automaton to get the precise pull request data matching the triggered commit.
```typescript
res.data.find((a) => a.head.sha === this.context.payload.workflow_run.head_sha)?.number as number;
```

**Comment by HarunamiYaki** [comment]
I noticed the code might be pulling the wrong pull request if there are multiple open PRs. When you're fetching the PR number using res.data[0].number, it might not always grab the right one if there are multiple open PRs. If the workflow gets triggered on `Pull Request #1` but you fetch res.data[0], it could mistakenly refer to `Pull Request #2`.

A possible fix could be filtering the data by `head_sha`. This tweak should help automaton to get the precise pull request data matching the triggered commit.
```typescript
res.data.find((a) => a.head.sha === this.context.payload.workflow_run.head_sha)?.number as number;
```

**Comment by Muunatic** [comment]
> I noticed the code might be pulling the wrong pull request if there are multiple open PRs. When you're fetching the PR number using res.data[0].number, it might not always grab the right one if there are multiple open PRs. If the workflow gets triggered on `Pull Request #1` but you fetch res.data[0], it could mistakenly refer to `Pull Request #2`.
> 
> A possible fix could be filtering the data by `head_sha`. This tweak should help automaton to get the precise pull request data matching the triggered commit.
> 
> ```ts
> res.data.find((a) => a.head.sha === this.context.payload.workflow_run.head_sha)?.number as number;
> ```

sounds good.

**Comment by HarunamiYaki** [comment]
Hey there! Just checking in on your pull request – any updates on this? Is it good to merge or are the tests still in progress?

**Comment by Muunatic** [comment]
ready to merge

**Pull request merged**
